### ISSUE TITLE
W10 DLL issues

### ISSUE THREAD

**Issue by GijsVermarien** [uclchem/SpectralRadex#10]
The builds for Windows 10 seem to work well, but it appears the spectralradex wrapper is never included in the path properly. 

```Python 3.10.10 | packaged by Anaconda, Inc. | (main, Mar 21 2023, 18:39:17) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import spectralradex
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\vermarien\AppData\Local\miniconda3\envs\spectralradex-1.1.5\lib\site-packages\spectralradex\__init__.py", line 2, in <module>
    from . import radex
  File "C:\Users\vermarien\AppData\Local\miniconda3\envs\spectralradex-1.1.5\lib\site-packages\spectralradex\radex\__init__.py", line 1, in <module>
    from radexwrap import *
ImportError: DLL load failed while importing radexwrap: The specified module could not be found.
```

A possible fix is: https://stackoverflow.com/a/72126318/8810578 but I am not sure how it interplays with the extension module, which will be deprecated anyway (https://github.com/uclchem/UCLCHEM/issues/30), so it could be addressed as a part of that revision.

**Comment by GijsVermarien** [comment]
After some discussion we decided to move to supporting WSL on Windows instead of building binaries for Windows.
